"""Generate a minimal Python card loader module from extracted card data."""

import json
from pathlib import Path


LOADER_TEMPLATE = '''\
"""Card loader for {game_name} — auto-generated by card_ingest utility.

Usage:
    from {module_name} import load_cards, get_cards_by_type, generate_deck

    cards = load_cards()
    troops = get_cards_by_type(cards, "troop")
    deck = generate_deck(cards)
"""

import json
import random
from pathlib import Path


CARDS_FILE = Path(__file__).parent / "cards.json"


def load_cards(path: str | None = None) -> list[dict]:
    """Load all cards from the JSON data file.

    Args:
        path: Override path to cards.json. Defaults to the file next to this module.
    """
    p = Path(path) if path else CARDS_FILE
    with open(p) as f:
        cards = json.load(f)
    # Strip internal metadata fields
    return [
        {{k: v for k, v in card.items() if not k.startswith("_")}}
        for card in cards
    ]


def get_cards_by_type(cards: list[dict], card_type: str) -> list[dict]:
    """Filter cards by their card_type field."""
    return [c for c in cards if c.get("card_type") == card_type]


def generate_deck(
    cards: list[dict],
    card_types: list[str] | None = None,
    shuffle: bool = True,
) -> list[dict]:
    """Create a deck from the card definitions.

    This is a basic stub — generates one copy of each card.
    Override or extend for games with multiple copies, variable deck
    composition by player count, etc.

    Args:
        cards: Full card list from load_cards().
        card_types: Only include these types. None = all types.
        shuffle: Shuffle the deck.
    """
    if card_types:
        deck = [c.copy() for c in cards if c.get("card_type") in card_types]
    else:
        deck = [c.copy() for c in cards]

    if shuffle:
        random.shuffle(deck)
    return deck
'''


def generate_parser(
    cards_json_path: str,
    output_path: str,
    game_name: str = "game",
) -> Path:
    """Generate a card_loader.py file alongside the cards.json.

    Args:
        cards_json_path: Path to the cards.json file (for validation).
        output_path: Where to write the loader module.
        game_name: Human-readable game name for the docstring.
    """
    # Validate that cards.json is loadable
    cards_path = Path(cards_json_path)
    if cards_path.exists():
        with open(cards_path) as f:
            cards = json.load(f)
        print(f"  Validated {len(cards)} cards in {cards_path.name}")

    module_name = Path(output_path).stem
    content = LOADER_TEMPLATE.format(game_name=game_name, module_name=module_name)

    out = Path(output_path)
    out.write_text(content)
    return out
